#! /bin/sh

# Append ROMIO library dependencies to the global list
EXTERNAL_LIBS="$EXTERNAL_LIBS -libmad -lrdmacm -libumad -libverbs -ldl -lrt -lm -lpthread  "

MPI_OFFSET_TYPE="long long"
FORTRAN_MPI_OFFSET="integer*8"
